/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_de_donnee;
import Application.BDD;
import Application.Parametre;
import Application.ResultSetTableModel;
//import Application.BDD.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Cachier extends javax.swing.JFrame {

    ResultSet rs,rm;
    BDD db;
    private int old;
    private int dec;
    private int now;
    /**
     * Creates new form Cachier
     */
    public Cachier() {
        db=new BDD(new Parametre().HOST_DB,new Parametre().USERNAME_DB,new Parametre().PASSWORD_DB,
                new Parametre().IPHOST,new Parametre().PORT); 
        initComponents();
        table();
        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void table(){
        String colon[] = {"code_produit" ,"reference" ,"desegnation" ,"rangement" ,"fournisseur","remise","prix","stock" };
        rs=db.querySelect(colon,"produit");
        table_prod.setModel(new Application.ResultSetTableModel(rs));
    
        String colo[] = {"num_facture","code_produit","reference","prix_vente" ,"stock_sortie","subtotal"};
        rm=db.querySelect(colo,"vente");
        table_ven.setModel(new Application.ResultSetTableModel(rm));
    
    
    
    }
    ////
       public void importer(){
        String colon[] = {"num_facture","code_produit","reference","prix_vente" ,"stock_sortie","subtotal"};
        rs=db.fcSelectCommand(colon,"vente","num_facture ='"+txt_fac.getText()+"'");
        table_ven.setModel(new Application.ResultSetTableModel(rs));}
       //////////////:
       public void jam(){
       Date s=new Date();
       SimpleDateFormat tgl=new SimpleDateFormat("EEEE-dd-MMM-yyyy");
              SimpleDateFormat jam=new SimpleDateFormat("HH:mm");
       lbl1.setText(jam.format(s));
       lb2.setText(tgl.format(s));}
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsto = new javax.swing.JTextField();
        jToggleButton5 = new javax.swing.JToggleButton();
        com_rech = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtrem = new javax.swing.JTextField();
        txtfou = new javax.swing.JTextField();
        txtpri = new javax.swing.JTextField();
        txtcod = new javax.swing.JTextField();
        txtref = new javax.swing.JTextField();
        txtran = new javax.swing.JTextField();
        txtnou1 = new javax.swing.JTextField();
        lbltot1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txt_cherche = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_ven = new javax.swing.JTable();
        jToggleButton6 = new javax.swing.JToggleButton();
        txt_cas = new javax.swing.JTextField();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbltot2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_fac = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 750));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(51, 255, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("cahier");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(390, 0, 70, 24);

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "reference", "desegnation", "rangement", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        table_prod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_prodKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 860, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("RP:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(160, 190, 60, 20);

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lbl1);
        lbl1.setBounds(530, 0, 110, 30);

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lbl2);
        lbl2.setBounds(550, 0, 110, 30);

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lbl3);
        lbl3.setBounds(540, 0, 110, 30);

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lbl4);
        lbl4.setBounds(530, 0, 110, 30);

        lb2.setText("jLabel16");
        jPanel2.add(lb2);
        lb2.setBounds(230, 0, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 11, 910, 150);

        jPanel3.setBackground(new java.awt.Color(204, 51, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 0));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("recherche par categorie:");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 10, 230, 24);

        txtsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstoActionPerformed(evt);
            }
        });
        txtsto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstoKeyReleased(evt);
            }
        });
        jPanel3.add(txtsto);
        txtsto.setBounds(110, 390, 190, 30);

        jToggleButton5.setText("recherche");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton5);
        jToggleButton5.setBounds(0, 70, 100, 30);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "code_produit", "reference", "deseignation", "rangement", "fournisseur", "remise", "prix", "stock" }));
        jPanel3.add(com_rech);
        com_rech.setBounds(10, 40, 240, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("code_produit:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 120, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("reference:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 160, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("fournisseur:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 240, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("remise:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 320, 70, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("nouveau prix:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 350, 110, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("stock sortie:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 390, 90, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("rangement:");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 200, 100, 20);

        jLabel13.setText("remise:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 0, 35, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("prix:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 270, 50, 20);

        txtrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremActionPerformed(evt);
            }
        });
        jPanel3.add(txtrem);
        txtrem.setBounds(110, 310, 190, 30);

        txtfou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfouActionPerformed(evt);
            }
        });
        jPanel3.add(txtfou);
        txtfou.setBounds(110, 230, 190, 30);

        txtpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriActionPerformed(evt);
            }
        });
        jPanel3.add(txtpri);
        txtpri.setBounds(110, 270, 190, 30);
        jPanel3.add(txtcod);
        txtcod.setBounds(110, 110, 190, 30);

        txtref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrefActionPerformed(evt);
            }
        });
        jPanel3.add(txtref);
        txtref.setBounds(110, 150, 190, 30);

        txtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtranActionPerformed(evt);
            }
        });
        jPanel3.add(txtran);
        txtran.setBounds(110, 190, 190, 30);

        txtnou1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnou1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtnou1);
        txtnou1.setBounds(110, 350, 190, 30);

        lbltot1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltot1.setText("0");
        jPanel3.add(lbltot1);
        lbltot1.setBounds(150, 420, 50, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("RP:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 430, 24, 17);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setText("ajouter au prouduit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton1);
        jToggleButton1.setBounds(100, 460, 160, 25);
        jPanel3.add(txt_cherche);
        txt_cherche.setBounds(110, 70, 190, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 170, 360, 480);

        jPanel4.setBackground(new java.awt.Color(204, 0, 204));
        jPanel4.setLayout(null);

        table_ven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "prix_vente", "stockage_sorte", "subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_venMouseClicked(evt);
            }
        });
        table_ven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_venKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table_ven);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 530, 100);

        jToggleButton6.setText("annuler");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton6);
        jToggleButton6.setBounds(180, 380, 170, 30);

        txt_cas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_casKeyReleased(evt);
            }
        });
        jPanel4.add(txt_cas);
        txt_cas.setBounds(60, 260, 150, 30);

        jToggleButton7.setText("supprimer");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton7);
        jToggleButton7.setBounds(430, 10, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("num_facture:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 14, 110, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("cash:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 260, 40, 30);

        lbltot2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltot2.setText("0");
        jPanel4.add(lbltot2);
        lbltot2.setBounds(300, 190, 70, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Total");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(20, 190, 100, 20);
        jPanel4.add(txt_fac);
        txt_fac.setBounds(110, 10, 190, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("payé apres:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(250, 260, 130, 30);
        jPanel4.add(txtpay);
        txtpay.setBounds(390, 260, 150, 30);

        jToggleButton8.setText("recherche");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton8);
        jToggleButton8.setBounds(320, 10, 100, 30);

        jToggleButton9.setText("Imprimer");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton9);
        jToggleButton9.setBounds(180, 330, 170, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("RP:");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(150, 200, 60, 20);

        jButton1.setText("CLose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(423, 373, 100, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(380, 170, 550, 470);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if(txt_cherche.getText().equals("")){
            JOptionPane.showMessageDialog(this,"S.V.P inserer la donnée à chercher !!");
        }else{
            if (com_rech.getSelectedItem().equals("id")){
                rs = db.querySelectAll("produit" , "id LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));

            }
            else if (com_rech.getSelectedItem().equals("code_produit")){
                rs = db.querySelectAll("produit" , "code_produit LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }

            else if (com_rech.getSelectedItem().equals("reference")){
                rs = db.querySelectAll("produit" , "reference LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if (com_rech.getSelectedItem().equals("desegnation")){
                rs = db.querySelectAll("produit" , "desegnation LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if (com_rech.getSelectedItem().equals("rangement")){
                rs = db.querySelectAll("produit" , "rangement LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if (com_rech.getSelectedItem().equals("fournisseur")){
                rs = db.querySelectAll("produit" , "fournisseur LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if (com_rech.getSelectedItem().equals("remise")){
                rs = db.querySelectAll("produit" , "remise LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if (com_rech.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("produit" , "prix LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if (com_rech.getSelectedItem().equals("stock")){
                rs = db.querySelectAll("produit" , "stock LIKE  '%" + txt_cherche.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void txtstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoActionPerformed

    private void txtrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrefActionPerformed

    private void txtremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremActionPerformed

    private void txtfouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfouActionPerformed

    private void txtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtranActionPerformed

    private void txtnou1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnou1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnou1ActionPerformed
   Statement st;
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
if(txtcod.getText().equals("") || txtref.getText().equals("") || txtran.getText().equals("") 
        ||txtfou.getText().equals("") || txtrem.getText().equals("") ||
        txtpri.getText().equals("") || txtnou1.getText().equals("") || txtsto.getText().equals("")){
        JOptionPane.showMessageDialog(this,"S.V.P entrez vos données ");
    }else if(txt_fac.getText().equals("")){
        JOptionPane.showMessageDialog(this,"S.V.P entrer le numéro de la facture ");
    }

else{
        
        double r=5.55;
        int h=(int)r;
    
            String num_fcture=txt_fac.getText();
            int code_produit=Integer.parseInt(txtcod.getText());
            String reference=txtref.getText();
            int prix_vente= Integer.parseInt(txtnou1.getText());
            int stock_sortie= Integer.parseInt(txtsto.getText());
            int subtotal = (int)Double.parseDouble(lbltot1.getText());
            
          String requetr="INSERT INTO `gestion_de_stock`.`vente` (`num_fcture`, `code_produit`, `reference`, `prix_vente`, `stock_sortie`, `subtotal`) VALUES ('"+num_fcture
           +"','"+code_produit+"','"+reference+"','"+prix_vente+"' ,'"+stock_sortie+"','"+subtotal+"');"; 
           try{
               st=db.connexionDatabase().createStatement();
               st.executeUpdate(requetr);
           
           }catch (SQLException ex) {
        System.err.println(ex);}
  
  /*     
        
        
    String[] colon={"num_fcture","code_produit","reference","prix_vente","stock_sortie","subtotal"};
    String[] isi={txt_fac.getText(),txtcod.getText(),txtref.getText(),txtnou1.getText(),
    txtsto.getText(),lbltot1.getText()};
    System.out.println(db.queryInsert("vente", colon, isi));
      */ 
        try {
           if(test_stock()) {
           JOptionPane.showMessageDialog(this,"le stock est limitter");}
           else {
               def();
               table();
           }
            }catch(SQLException e){
           Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE,null,e);
           System.err.println("\n"+e);} 
       subtotal();
       importer();
       total();
           }
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
String invoice=txt_fac.getText();
if(JOptionPane.showConfirmDialog(this,"est ce que tu es sure que tu veux supprimer"
        ,"attention",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
db.queryDelet("vente","num_facture="+invoice);}
else {return;}
importer();
total();
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
    String id=String.valueOf(table_ven.getValueAt(table_ven.getSelectedRow(),0));
    if(JOptionPane.showConfirmDialog(this,"Attention vous allez supprimer vos données","Attention"
        ,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
        db.queryDelet("vente","id ="+id);}
    else{return;}
    importer();
    total();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed

        importer();total();
        
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
  recu d=new recu();
 d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void txtpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
txtcod.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),0)));
txtref.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),1)));
txtran.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),3)));
txtpri.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),4)));
txtrem.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),5)));
txtsto.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),6)));
cout();
        // TODO add your handling code here:
    }//GEN-LAST:event_table_prodMouseClicked

    private void txtstoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstoKeyReleased
     
        subtotal();
        
    }//GEN-LAST:event_txtstoKeyReleased

    private void txt_casKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_casKeyReleased
              
       payapres(); 
        
    }//GEN-LAST:event_txt_casKeyReleased

    private void table_prodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_prodKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_table_prodKeyReleased

    private void table_venKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_venKeyReleased

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_table_venKeyReleased

    private void table_venMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_venMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_venMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void subtotal(){
    double a=Integer.parseInt(txtnou1.getText());
    double b=Integer.parseInt(txtsto.getText());
    double c=a*b;
    lbltot1.setText(String.valueOf(c));}
    
    
    public boolean test_stock() throws SQLException {
    boolean teststock;
    rs=db.querySelectAll("produit","code_produit = '"+txtcod.getText()+"'");
    while(rs.next()){
         old=rs.getInt("stock");
        }
            dec=Integer.parseInt(txtsto.getText());
            if(old<dec){
    teststock=false;   ////////////////////////////**********************************
            }
    else{teststock=true;}
    return teststock;
    }
    

    //
    public void def() throws SQLException{
    rs=db.querySelectAll("produit","code_produit = '"+txtcod.getText()+"'");
    while(rs.next()){
    old=rs.getInt("stock");}
    dec=Integer.parseInt(txtsto.getText());
    now=old-dec;
    String  nvstock=Integer.toString(now);
    String a=String.valueOf(nvstock);
    String[] colon={"stock"};
    String[] isi={a};
    System.out.println(db.queryUpdate("produit",colon,isi,"code_produit='"+txtcod.getText()+"'"));
            }
    //
    
    public void total(){
    rs=db.executionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture='"
            +txt_fac.getText()+"'");
    try{
        rs.next();
        lbltot2.setText(rs.getString("subtotal"));
    }catch(SQLException ex){
    Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE,null,ex);}
    }
    //:::://///
    
    public void payapres(){
    int a=Integer.parseInt(lbltot2.getText());
    int b=Integer.parseInt(txt_cas.getText());
    int c=b-a;
    txtpay.setText(Integer.toString(c));}
    ////////////////////////
    
    public void cout(){
    double a= Double.parseDouble(txtpri.getText());
    double b=Double.parseDouble(txtrem.getText());
    double c=a-a*(b/100);
    txtnou1.setText(String.valueOf(c));}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cachier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox com_rech;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    public static javax.swing.JLabel lb2;
    public static javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private static javax.swing.JLabel lbltot1;
    public static javax.swing.JLabel lbltot2;
    private javax.swing.JTable table_prod;
    private javax.swing.JTable table_ven;
    public static javax.swing.JTextField txt_cas;
    private javax.swing.JTextField txt_cherche;
    public static javax.swing.JTextField txt_fac;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtfou;
    private static javax.swing.JTextField txtnou1;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtpri;
    private javax.swing.JTextField txtran;
    private javax.swing.JTextField txtref;
    private javax.swing.JTextField txtrem;
    private static javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
