/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_de_donnee;
import Application.BDD;
import Application.Parametre;
import Application.ResultSetTableModel;
import java.sql.ResultSet;

public class recu extends javax.swing.JFrame {
ResultSet rs;
BDD db;
    public recu() {
        db=new BDD(new Parametre().HOST_DB,new Parametre().USERNAME_DB,new Parametre().PASSWORD_DB,
                new Parametre().IPHOST,new Parametre().PORT); 
        initComponents();
        table();
    
        importer();
        //date();
        }
    
    
    
    
    public void table(){
        String colo[] = {"num_facture","code_produit","reference","prix_vente" ,"stock_sortie","subtotal"};
        rs=db.querySelect(colo,"vente");
        tbleImp.setModel(new Application.ResultSetTableModel(rs));
    
    
    
    }
    
    
    
    
   public void  importer(){
        String colon[]={"num_facture","code_produit","reference","prix_vente",
        "stock_sortir","subtotal"};
         rs=db.fcSelectCommand(colon,"vente","num_facture='"+Cachier.txt_fac.getText()+"'");
        tbleImp.setModel(new ResultSetTableModel(rs));
         lbltot.setText(Cachier.lbltot2.getText());
       lblcas.setText(Cachier.txt_cas.getText());
        paypres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbleImp = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbltot = new javax.swing.JLabel();
        lblcas = new javax.swing.JLabel();
        lblpay = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();

        recu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recu.setText("recu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setLayout(null);

        tbleImp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "prix_vente", "stockage_sorte", "subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbleImp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleImpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbleImp);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 40, 440, 100);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 150, 90, 21);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 190, 90, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Total:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 154, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("payé");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 190, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Payé aprés:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 220, 80, 30);

        lbltot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot.setText("0000");
        jPanel1.add(lbltot);
        lbltot.setBounds(250, 150, 100, 30);

        lblcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcas.setText("000");
        jPanel1.add(lblcas);
        lblcas.setBounds(250, 180, 100, 30);

        lblpay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpay.setText("0000");
        lblpay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblpay);
        lblpay.setBounds(260, 220, 90, 30);
        jPanel1.add(lbld);
        lbld.setBounds(310, 10, 70, 30);
        jPanel1.add(lblh);
        lblh.setBounds(70, 10, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 1, 470, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Cachier p=new Cachier();
p.setVisible(true);
this.dispose();
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.printComponents(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbleImpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleImpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbleImpMouseClicked

    public void date(){
    lbld.setText(Cachier.lbl1.getText());
    lblh.setText(Cachier.lb2.getText());
    }
    
    public void paypres(){
    int a=Integer.parseInt((Cachier.lbltot2.getText()));
    int b=Integer.parseInt(Cachier.txt_cas.getText());
    int c=b-a;
    lblpay.setText(Integer.toString(c));}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcas;
    private javax.swing.JLabel lbld;
    private javax.swing.JLabel lblh;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lbltot;
    private javax.swing.JLabel recu;
    private javax.swing.JTable tbleImp;
    // End of variables declaration//GEN-END:variables
}
