
package Base_de_donnee;

import Application.BDD;
import Application.Parametre;
import Application.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane;





public class Utilisateur extends javax.swing.JFrame {
// declaration des variables :
    Statement st;
   
    ResultSet rs;
    BDD db;
    
    
    public Utilisateur() {
        db=new BDD(new Parametre().HOST_DB,new Parametre().USERNAME_DB,new Parametre().PASSWORD_DB,
                new Parametre().IPHOST,new Parametre().PORT); 
        initComponents();
      
        table();
    }
    
    // selection ou afficher le tableau
    public void table(){
        String a[] = {"id" ,"id_user" ,"username" ,"password" ,"type" };
        rs=db.querySelect(a, "utilisateur");
        table_user.setModel(new ResultSetTableModel(rs));
       
    }
    // methode actualiser :
     void actualiser(){
        
     txt_id.setText("");
     txt_us.setText("");
     txt_pa.setText("");
     com_ty.setSelectedItem("Tyyype");
     
     
     }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_us = new javax.swing.JTextField();
        txt_rech = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt_pa = new javax.swing.JTextField();
        com_rech = new javax.swing.JComboBox();
        com_ty = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(750, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Gestion des Utilisateur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 270, 28);

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "id_user", "username", "password", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 650, 110);

        jButton1.setForeground(new java.awt.Color(51, 153, 0));
        jButton1.setText("Recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 350, 110, 30);

        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 190, 100, 30);

        jButton3.setForeground(new java.awt.Color(102, 153, 0));
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 190, 100, 30);

        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 190, 90, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 410, 80, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Recherche selon :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 300, 230, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 320, 80, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 370, 80, 20);

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(140, 260, 110, 30);

        txt_us.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usActionPerformed(evt);
            }
        });
        getContentPane().add(txt_us);
        txt_us.setBounds(140, 310, 110, 30);

        txt_rech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rech);
        txt_rech.setBounds(500, 350, 130, 30);

        jButton5.setForeground(new java.awt.Color(51, 153, 0));
        jButton5.setText("actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(420, 190, 90, 30);

        txt_pa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pa);
        txt_pa.setBounds(140, 360, 110, 30);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id_user", "username\t", "password", "type" }));
        com_rech.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(com_rech);
        com_rech.setBounds(500, 300, 140, 30);

        com_ty.setForeground(new java.awt.Color(102, 153, 0));
        com_ty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employer", "Directeur" }));
        com_ty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(com_ty);
        com_ty.setBounds(140, 410, 110, 30);

        jLabel6.setBackground(new java.awt.Color(204, 0, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 255));
        jLabel6.setText("id_user");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 270, 80, 20);

        retour.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        retour.setForeground(new java.awt.Color(51, 204, 255));
        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(560, 410, 101, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               if(txt_rech.getText().equals("")){
                   JOptionPane.showMessageDialog(this,"S.V.P inserer la donnée à chercher !!");
               }else{
                   if (com_rech.getSelectedItem().equals("id_user")){
                      rs = db.querySelectAll("utilisateur" , "id_user LIKE  '%" + txt_rech.getText() + "%' ");
                       table_user.setModel(new ResultSetTableModel(rs));
                       
                     }
                   else if (com_rech.getSelectedItem().equals("username")){
                      rs = db.querySelectAll("utilisateur" , "username LIKE  '%" + txt_rech.getText() + "%' ");
                       table_user.setModel(new ResultSetTableModel(rs));
                      }
                   else if (com_rech.getSelectedItem().equals("password")){
                      rs = db.querySelectAll("utilisateur" , "password LIKE  '%" + txt_rech.getText() + "%' ");
                       table_user.setModel(new ResultSetTableModel(rs));
                      }
                   else if (com_rech.getSelectedItem().equals("type")){
                      rs = db.querySelectAll("utilisateur" , "type LIKE  '%" + txt_rech.getText() + "%' ");
                       table_user.setModel(new ResultSetTableModel(rs));
                   }
               }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if( txt_id.getText().equals("") || txt_us.getText().equals("") || txt_pa.getText().equals("")  ||  com_ty.getSelectedItem().equals("Tyyype")){
            JOptionPane.showMessageDialog(this ," Entrez les donner complete S.V.P !");
        }
        else{
            String[] colon = {"id_user", "username" , "password", "type" };
            String[] inf = { txt_id.getText(),txt_us.getText(),txt_pa.getText() ,com_ty.getSelectedItem().toString()};
            String   id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
            System.out.println(db.queryUpdate( " utilisateur", colon , inf, "id= '" +id + "'"));
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String   id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this,"est ce que vous êtes sure de supprimer !","Attention !!",
                JOptionPane.OK_CANCEL_OPTION ) == JOptionPane.OK_OPTION ){
             String requetr="DELETE FROM `gestion_de_stock`.`utilisateur` WHERE id= '"+id+"';";
             try{st=db.connexionDatabase().createStatement();
               st.executeUpdate(requetr);
             }catch(SQLException e){
                 System.err.println(e);
             }
             /*   db.queryDelet( "utilisateur" , "id =" +id); */
        }else {
            return;
        }
        table();
        actualiser();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usActionPerformed

    private void txt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        actualiser();
        table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_paActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      

        
        if( txt_id.getText().equals("") || txt_us.getText().equals("") || txt_pa.getText().equals("")  ||  com_ty.getSelectedItem().equals("Tyyype")){
            JOptionPane.showMessageDialog(this ," Entrez les donner complete S.V.P !");
        }
        else{
            
            
            String id_user=txt_id.getText();
            String username=txt_us.getText();
            String password=txt_pa.getText();
            String type= com_ty.getSelectedItem().toString();
          String requetr="INSERT INTO `gestion_de_stock`.`utilisateur` (`id_user`, `username`, `password`, `type`) VALUES ('"+id_user+"','"+username+"','"+password+"','"+type+"');"; 
           try{
               st=db.connexionDatabase().createStatement();
               st.executeUpdate(requetr);
           
           }catch (SQLException ex) {
        System.err.println(ex);
  
               
               }
            
            
            
           /*
            String[] colon ={"id_user", "username" , "password", "type" };
            String[] inf ={ txt_id.getText() ,txt_us.getText() ,txt_pa.getText() ,com_ty.getSelectedItem().toString()};
            db.queryInsert(" utilisateur ",colon,inf);
            System.out.println(db.queryInsert(" utilisateur ",colon,inf));
           */
            actualiser();
            table();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
      txt_id.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),1)));
      txt_us.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),2)));
      txt_pa.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),3)));
      com_ty.setSelectedItem(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),4)));
     
      
      
      
    }//GEN-LAST:event_table_userMouseClicked

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        Principale a = new Principale();
        a.setVisible(false);
       
        this.dispose();
        
    }//GEN-LAST:event_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox com_rech;
    private javax.swing.JComboBox com_ty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retour;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_pa;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_us;
    // End of variables declaration//GEN-END:variables
}
